/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.LoginUI;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import com.payroll.ui.DashboardFrame;
import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.io.File;

/**
 *
 * @author ongoj
 */
public class LoginUI extends javax.swing.JFrame {

    // ────── CUSTOM FIELDS ─────────────────────────────────────────────────────
    /** CSV‐backed username/password store */
    private Map<String,String> credentials = new HashMap<>();
    // ────────────────────────────────────────────────────────────────────────────

    /** Creates new form LoginUI */
    public LoginUI() {
        initComponents();

    // generated code – sets up jTextField1, jPasswordField1, etc.
    // placeholder & focus logic goes here
    jTextField1.setForeground(Color.GRAY);
    // … rest of that FocusListener code …

    jPasswordField1.setForeground(Color.GRAY);
    // … rest of the password FocusListener code …
        
        // 1) Load credentials from root‐level CSV
        loadCredentialsFromCSV("UserLogIns.csv");
        
        // 2) Hide the spinner until login is attempted
        jProgressBar1.setVisible(false);

        // 3) Single‐Enter to click Login
        getRootPane().setDefaultButton(jButton1);

        // 4) Tooltips for format hints
        jTextField1.setToolTipText(
            "Format: EmployeeNumber\n(e.g. 000000)"
        );
        jPasswordField1.setToolTipText(
            "Format: NameInitials+Emp#+BirthYear!\n(e.g. JR100351861!)"
        );
        
        // in LoginUI() constructor, after initComponents():

    // Make the field show a gray "USERNAME" placeholder
    jTextField1.setForeground(Color.GRAY);
    jTextField1.setText("USERNAME");
    jTextField1.addFocusListener(new FocusAdapter() {
        @Override
        public void focusGained(FocusEvent e) {
            if (jTextField1.getText().equals("USERNAME")) {
                jTextField1.setText("");
                jTextField1.setForeground(Color.BLACK);
            }
        }
        @Override
        public void focusLost(FocusEvent e) {
            if (jTextField1.getText().isEmpty()) {
                jTextField1.setForeground(Color.GRAY);
                jTextField1.setText("USERNAME");
            }
        }
    });

    // Do the same for password, but manage echo char so placeholder is visible:
    jPasswordField1.setForeground(Color.GRAY);
    jPasswordField1.setEchoChar((char)0);          // show text
    jPasswordField1.setText("PASSWORD");
    jPasswordField1.addFocusListener(new FocusAdapter() {
        @Override
        public void focusGained(FocusEvent e) {
            String pwd = new String(jPasswordField1.getPassword());
            if (pwd.equals("PASSWORD")) {
                jPasswordField1.setText("");
                jPasswordField1.setForeground(Color.BLACK);
                jPasswordField1.setEchoChar('•');    // or '*' 
            }
        }
        @Override
        public void focusLost(FocusEvent e) {
            String pwd = new String(jPasswordField1.getPassword());
            if (pwd.isEmpty()) {
                jPasswordField1.setForeground(Color.GRAY);
                jPasswordField1.setEchoChar((char)0); // show placeholder
                jPasswordField1.setText("PASSWORD");
            }
        }
    });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/LoginUI/images/motorph.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/LoginUI/images/motorph.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PAYROLL SYSTEM");
        jLabel3.setToolTipText("Format: F.LastNameEmployeeNumber (e.g. J.Rizal00001) ");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/LoginUI/images/username.png"))); // NOI18N
        jLabel4.setLabelFor(jTextField1);
        jLabel4.setToolTipText("Format: FLastNameEmployeeNumber (ex. JRizal00001) ");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/LoginUI/images/password.png"))); // NOI18N
        jLabel5.setLabelFor(jPasswordField1);
        jLabel5.setToolTipText("Format: FLNumberBirthYear! (ex. JR100351861!) ");

        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setToolTipText("");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setToolTipText("");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/LoginUI/images/login.png"))); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(12, 12, 12)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(12, 12, 12)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /** Login button handler */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // show spinner
        jProgressBar1.setVisible(true);
        jProgressBar1.setIndeterminate(true);

        String user = jTextField1.getText().trim();
        String pass = new String(jPasswordField1.getPassword());

        if (credentials.containsKey(user) && credentials.get(user).equals(pass)) {
            JOptionPane.showMessageDialog(this, "Login successful.", "Welcome", JOptionPane.INFORMATION_MESSAGE);
            new DashboardFrame().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password.", "Error", JOptionPane.ERROR_MESSAGE);
            jPasswordField1.setText("");
        }

        // hide spinner
        jProgressBar1.setIndeterminate(false);
        jProgressBar1.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed
    // ────── CUSTOM METHOD ──────────────────────────────────────────────────────
    /** Reads username/password pairs from a CSV at the project root */
    private void loadCredentialsFromCSV(String path) {
    credentials.clear();
    try (BufferedReader br = new BufferedReader(new FileReader(path))) {
        // Skip the header row
        String line = br.readLine();
        if (line != null && line.startsWith("\uFEFF")) {
            // strip BOM if present
            line = line.substring(1);
        }

        // Now read each data row
        while ((line = br.readLine()) != null) {
            String[] parts = line.split(",");
            if (parts.length < 2) continue;              // malformed row
            String user = parts[0].trim();
            if (user.equalsIgnoreCase("username")) continue; // safety skip

            String pass = parts[1].trim();
            credentials.put(user, pass);
        }

        System.out.println("Loaded credentials: " + credentials.keySet());
    } catch (IOException ex) {
        JOptionPane.showMessageDialog(this,
            "Error loading credentials:\n" + ex.getMessage(),
            "Load Error", JOptionPane.ERROR_MESSAGE);
    }
}

    // ────────────────────────────────────────────────────────────────────────────

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
