/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author ongoj
 */
 
package com.gui.Home;
import com.opencsv.CSVReader;
import com.opencsv.exceptions.CsvValidationException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.FileReader;
import java.io.IOException;

public class ChangeLogs extends javax.swing.JPanel {

        private JTable logTable;
        private DefaultTableModel tableModel;
    
    /**
     * Creates new form ChangeLogs
     */
    public ChangeLogs() {
        initComponents();
        setupTable();
        loadChangeLogs(); // Load data when panel is created
    }
    private void setupTable() {
    // Initialize table and model
    tableModel = new DefaultTableModel();
    logTable = new JTable(tableModel);

    // Add the table to a scroll pane and add to this panel
    JScrollPane scrollPane = new JScrollPane(logTable);
    this.setLayout(new java.awt.BorderLayout());
    this.add(scrollPane, java.awt.BorderLayout.CENTER);
    }

    public void loadChangeLogs() {
                tableModel.setRowCount(0);
        try (CSVReader reader = new CSVReader(new FileReader("src/com/csv/EmpDataChangeLogs.csv"))) {
            String[] nextLine;
            boolean isHeader = true;
            while ((nextLine = reader.readNext()) != null) {
                if (isHeader) {
                    tableModel.setColumnIdentifiers(nextLine); // Set header
                    isHeader = false;
                } else {
                    tableModel.addRow(nextLine);
                }
            }
        } catch (IOException | CsvValidationException e) {
            JOptionPane.showMessageDialog(this, "Error loading change logs: " + e.getMessage());
        }

    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}